name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: ./go.mod
    - name: Build stldevs
      run: CGO_ENABLED=0 go build cmd/stldevs/stldevs.go
    - name: Build gatherer
      run: CGO_ENABLED=0 go build cmd/gather/gather.go
    - uses: actions/upload-artifact@v4
      with:
        name: dist
        path: |
          stldevs
          gather

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
      - name: Test
        run: sh test.sh

  deploy:
    if: github.event_name != 'pull_request'
    needs: [build,test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: dist
    - name: Deploy
      uses: appleboy/scp-action@master
      with:
        host: stldevs.com
        username: deploy
        key: ${{ secrets.KEY }}
        port: 22
        source: "stldevs,gather"
        target: "~"

    - name: Restart
      uses: appleboy/ssh-action@master
      with:
        host: stldevs.com
        username: deploy
        key: ${{ secrets.KEY }}
        port: 22
        script: |
          sudo service stldevs stop
          mv -f ~/stldevs /opt/stldevs
          mv -f ~/gather /opt/stldevs
          cd /opt/stldevs
          chmod +x stldevs
          chmod +x gather
          sudo service stldevs start
